test_and_learn_v2/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tl/', include('tl.urls')),
]

tl/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView, name='detail'),
    url(r'^newtest/$', views.newtest, name='newtest'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.UpdateView, name='update'),
    url(r'^query/$', views.QueryView, name='query'),

]


# urlpatterns = [
#     url(r'^$', views.home, name='home'),
#     url(r'^newtest/$', views.testsCreateView, name='newtest'),
#     url(r'^modifytest/$', views.testsUpdateView, name='modifytest'),

# ]

tl/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models

# Create your models here.


TYPE_CHOICES = (
    ('vsCntrl', 'vsCntrl'),
    ('Sales', 'Sales'),
)

TEST_TYPE_CHOICES = (
    ('T&L', 'T&L'),
    ('CPG', 'CPG'),
    ('Field', 'Field'),

)

MERCH_GROUP_CHOICES =(
    ('Health Care', 'Health Care'),
    ('Consumables', 'Consumables'),
    ('Beauty/Personal', 'Beauty/Personal'),
    ('General Merchandising', 'General Merchandising'),
)

SUCCESS_METRIC_CHOICES = (
    ('Sales Lift', 'Sales Lift'),
    ('Other', 'Other'),
)

class Test(models.Model):
    test_no	= models.IntegerField(primary_key=True)
    type = models.CharField(max_length=50, choices=TYPE_CHOICES)
    test_name = models.CharField(max_length=100)
    test_desc = models.CharField(max_length=250)	
    merch_group = models.CharField(max_length=50, choices=MERCH_GROUP_CHOICES)
    success_metric = models.CharField(max_length=50, choices=SUCCESS_METRIC_CHOICES)
    success_desc = models.CharField(max_length=100)
    success_value	= models.IntegerField(default=0)
    test_type = models.CharField(max_length=50, choices=TEST_TYPE_CHOICES)

    def __unicode__(self):
        return unicode(self.test_no)

class Sponsor(models.Model):
    test_no = models.IntegerField()
    sponsors = models.CharField(max_length=50)



class Store(models.Model):
    test_no = models.IntegerField()
    location_id = models.IntegerField()
    test_store = models.BooleanField(default=0)
    pair = models.IntegerField()
    wave_no = models.IntegerField()



class WaveDate(models.Model):
    test_no = models.IntegerField()
    wave_no = models.IntegerField()
    wave_value = models.CharField(max_length=100)
    pre_start = models.DateField("Pre Period Start Date")
    pre_end = models.DateField()
    post_start = models.DateField()
    post_end = models.DateField()



class Product(models.Model):
    test_no = models.IntegerField()
    product_no = models.IntegerField()
    product_level_no = models.IntegerField()
    product_tier = models.IntegerField()
    group_no = models.IntegerField()

tl/forms.py
#from django.forms import forms, ModelForm
from django import forms
from .models import Test, WaveDate, Sponsor



class TestForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = ['test_no', 'type', 'test_name', 'test_desc', 'merch_group', 'success_metric', 'success_desc', 'success_value', 'test_type']
        labels = {'test_no': 'Test Number',
                  'type': 'Test Type',
                  'test_name': 'Test Name',
                  'test_desc': 'Test Description',
                  'merch_group': 'Merchandise Group',
                  'success_metric': 'Success Metric',
        }

class SponsorForm(forms.ModelForm):
    class Meta:
        model = Sponsor
        fields = ['sponsors']
        labels = {'sponsors': 'Sponsors',
        }

class WaveDateForm(forms.ModelForm):
	class Meta:
		model = WaveDate
		fields = ['wave_no', 'wave_value','pre_start','pre_end','post_start','post_end']
		wigets = {'pre_start': forms.SelectDateWidget}


SUPER_CATEGORY_CHOICES = (
	(1, 'CONSUMER HEALTH CARE'),
	(2, 'BEAUTY CARE'),
	(3, 'GENERAL MERCHANDISE'),
	(4, 'EDIBLES'),
	(5, 'GREETING CARDS'),
	(6, 'PHOTO'),
	(7, 'PERSONAL CARE'),
)



class ProductForm(forms.Form):
    super_category_tier1 = forms.MultipleChoiceField(widget = forms.CheckboxSelectMultiple, label='Super Category', choices=SUPER_CATEGORY_CHOICES, required=False)
    category_tier1 = forms.IntegerField(label='Category', required=False)
    sub_category_tier1 = forms.IntegerField(label='Sub Category', required=False)
    segment_tier1 = forms.IntegerField(label='Segment', required=False)
    sku_tier1 = forms.IntegerField(label = 'SKU', required=False)
    group_tier1 = forms.BooleanField(label = 'Group Tier 1 Products', required=False)
    
    super_category_tier2 = forms.MultipleChoiceField(widget = forms.CheckboxSelectMultiple, label='Super Category', choices=SUPER_CATEGORY_CHOICES, required=False)
    category_tier2 = forms.IntegerField(label='Category', required=False)
    sub_category_tier2 = forms.IntegerField(label='Sub Category', required=False)
    segment_tier2 = forms.IntegerField(label='Segment', required=False)
    sku_tier2 = forms.IntegerField(label = 'SKU', required=False)

class StoreForm(forms.Form):
	store_list = forms.FileField()

tl/views.py
import os
import csv

from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views.generic import UpdateView, DetailView, ListView
from django.db import connection


from .models import Test, WaveDate, Product, Store
from .forms import TestForm, WaveDateForm, ProductForm, StoreForm, SponsorForm


# Create your views here.

def home(request):
    #context = {'latest_question_list': latest_question_list}
    return render(request, 'tl/home.html')


class IndexView(ListView):
    template_name = 'tl/index.html'
    model = Test


def DetailView(request, pk):
    test = get_object_or_404(Test, pk=pk)
    #form = TestForm(instance=test)
    return render(request, 'tl/detail.html', {'test': test})


# class UpdateView(UpdateView):
#     model = Test
#     form_class = TestForm
#     template_name = 'tl/edit.html'


def UpdateView(request, pk):
    test = get_object_or_404(Test, pk=pk)
    if request.method == 'POST':
        test_form = TestForm(request.POST, instance=test)

        if test_form.is_valid():
            test = test_form.save()
            return redirect('/tl/', pk=test.pk)
    else:
        test_form = TestForm(instance=test)
    return render(request, 'tl/edit.html', {'test_form': test_form})



def newtest(request):
    if request.method == 'POST':
        test_form = TestForm(request.POST)
        sponsor_form = SponsorForm(request.POST)
        wavedate_form = WaveDateForm(request.POST)
        product_form = ProductForm(request.POST)
        store_form = StoreForm(request.POST, request.FILES) 

        if test_form.is_valid() and wavedate_form.is_valid() and product_form.is_valid() and store_form.is_valid() and sponsor_form.is_valid():
            test = test_form.save()
            test.save()

            sponsor = sponsor_form.save(commit=False)
            sponsor.test_no = test.test_no
            sponsor.save()

            wave = wavedate_form.save(commit=False)
            wave.test_no = test.test_no
            wave.save()

            # Tier 1 Proudcts
            super_category_list = product_form.cleaned_data['super_category_tier1']
            if super_category_list:
                for i in super_category_list:
                    p1 = Product(test_no=test.test_no, product_no=i, product_level_no=2,product_tier=1, group_no=1)
                    p1.save()

            category = product_form.cleaned_data['category_tier1']
            if category:
                p2 = Product(test_no=test.test_no, product_no=category, product_level_no=3,product_tier=1, group_no=1)
                p2.save()

            sub_category = product_form.cleaned_data['sub_category_tier1']
            if sub_category:
                p3 = Product(test_no=test.test_no, product_no=sub_category, product_level_no=4,product_tier=1, group_no=1)
                p3.save()

            segment = product_form.cleaned_data['segment_tier1']
            if segment:
                p4 = Product(test_no=test.test_no, product_no=segment, product_level_no=5,product_tier=1, group_no=1)
                p4.save()

            sku = product_form.cleaned_data['sku_tier1']
            if sku:
                p5 = Product(test_no=test.test_no, product_no=sku, product_level_no=7,product_tier=1, group_no=1)
                p5.save()

            # Tier 2 Proudcts
            super_category_list = product_form.cleaned_data['super_category_tier2']
            if super_category_list:
                for i in super_category_list:
                    p1 = Product(test_no=test.test_no, product_no=i, product_level_no=2,product_tier=2, group_no=i)
                    p1.save()

            category = product_form.cleaned_data['category_tier2']
            if category:
                p2 = Product(test_no=test.test_no, product_no=category, product_level_no=3,product_tier=2, group_no=category)
                p2.save()

            sub_category = product_form.cleaned_data['sub_category_tier2']
            if sub_category:
                p3 = Product(test_no=test.test_no, product_no=sub_category, product_level_no=4,product_tier=2, group_no=sub_category)
                p3.save()

            segment = product_form.cleaned_data['segment_tier2']
            if segment:
                p4 = Product(test_no=test.test_no, product_no=segment, product_level_no=5,product_tier=2, group_no=segment)
                p4.save()

            sku = product_form.cleaned_data['sku_tier2']
            if sku:
                p5 = Product(test_no=test.test_no, product_no=sku, product_level_no=7,product_tier=2, group_no=sku)
                p5.save()


            # Load store list
            store_list = store_form.cleaned_data['store_list']
            data = csv.DictReader(store_list)
            for row in data:
                Store.objects.create(
                test_no=test.test_no,
                location_id=row['location_id'],
                test_store=row['test_store'],
                pair=row['pair'],
                wave_no=row['wave_no'])
    else:
        test_form = TestForm()
        wavedate_form = WaveDateForm()
        product_form = ProductForm()
        store_form = StoreForm() 
        sponsor_form = SponsorForm() 

    return render(request, 'tl/newtest.html', {'test_form': test_form, 
                                               'wavedate_form': wavedate_form, 
                                               'product_form': product_form, 
                                               'store_form': store_form,
                                               'sponsor_form': sponsor_form,
                                               })


def QueryView(request):
    cursor = connection.cursor()

    cursor.execute("SELECT location_key, SUM(spend) AS total_spend FROM item_fact_sample GROUP BY 1")

    context = cursor.fetchall()

    return render(request, 'tl/query.html', {'context': context})

tl/templates/tl/UpdateTest.html
Hello

<!-- <form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form> -->

tl/templates/tl/base.html
{% load staticfiles %}

<link rel="stylesheet" href="{% static 'tl/bootstrap.css' %}" />
<link rel="stylesheet" href="{% static 'tl/style.css' %}" />



<html lang="en">

	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#">Brand</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li><a href="/tl/">Home</a></li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li><a href="#">Query Stores</a></li>
	            <li><a href="#">Another action</a></li>
	            <li><a href="#">Something else here</a></li>
	            <li role="separator" class="divider"></li>
	            <li><a href="#">Separated link</a></li>
	            <li role="separator" class="divider"></li>
	            <li><a href="#">One more separated link</a></li>
	          </ul>
	        </li>
	      </ul>
	      <form class="navbar-form navbar-left" role="search">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Search">
	        </div>
	        <button type="submit" class="btn btn-default">Submit</button>
	      </form>
	      <ul class="nav navbar-nav navbar-right">
	        <li><a href="#">Link</a></li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li><a href="#">Action</a></li>
	            <li><a href="#">Another action</a></li>
	            <li><a href="#">Something else here</a></li>
	            <li role="separator" class="divider"></li>
	            <li><a href="#">Separated link</a></li>
	          </ul>
	        </li>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>



	<head>
	    <title>CVS Test & Learn</title>
	</head>
	<body>
		<div class="container-fluid">
			<div class="row"> 
				<div class="col-md-2">
					<img src="/static/tl/images/cvs_health_reg_img.png" class="img-responsive">
				</div> 		
				<div class="col-md-10 text-right text-uppercase">
					<h1>Test & Learn</h1>
					<h4>Data Management</h4>
				</div>	
				<div class="row">
					<div class="col-md-12">
						<hr>
					</div>	
				</div>	
			</div>
			{% block content %}
            {% endblock %}
		</div>
	</body>	

tl/templates/tl/detail.html
{% extends 'tl/base.html' %}
{% load crispy_forms_tags %}


{% block content %}

<a class="btn btn-default" href="{% url 'tl:update' pk=test.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>

<p>{{ test.test_no }}</p>


{% endblock %}

tl/templates/tl/edit.html
{% extends 'tl/base.html' %}
{% load crispy_forms_tags %}


{% block content %}

<form enctype="multipart/form-data" method="POST" class="post-form"> {% csrf_token %}

<div class="row">
	<div class="col-md-4">	
		<p>{{ test_form|crispy }}</p>

	<button type="submit" class="save btn btn-default"> Save </button>
	</div>
</div>
</form>

{% endblock %}

tl/templates/tl/home.html
{% extends 'tl/base.html' %}



{% block content %}

<div class="row">
	<div class="col-md-12">
		<p>This will be an informational paragraph with instructions. Not Sure what this space will contain!!!!</p>
	</div>	
</div>	
<div class="row">
	<div class="col-md-3">
		<a class="btn btn-default" href="http://localhost:8000/tl/newtest/" role="button"> Create a New Test</a>
	</div>
	<div class="col-md-9">
		<p>Informational paragraph</p>
	</div>	
</div>
<div class="row">
	<div class="col-md-3">
		<a class="btn btn-default" href="http://localhost:8000/tl/updatetest/" role="button"> Update an Existing Test</a>					
	</div>
	<div class="col-md-9">
		<p>Informational paragraph</p>
	</div>	
</div>
<div class="row">
	<div class="col-md-3">
		<h4>Other</h4>					
	</div>
	<div class="col-md-9">
		<p>Informational paragraph</p>					
	</div>	
</div>


{% endblock %}

tl/templates/tl/index.html
{% extends 'tl/base.html' %}

{% block content %}

<div class="jumbotron">
	<div class="row"> 
		<div class="col-md-6">
			<h2>Test & Learn</h2>
			<h2>Data Management</h2>
			<p>...</p>
     		<p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
		</div>

		<div class="col-md-6">
  			<img src="/static/tl/images/cvs_health_reg_img.png" class="img-responsive">
		</div>
  	</div>
</div>


</div>	
<div class="row">

	<div class="col-md-6">
		<a class="btn btn-large btn-default" href="http://localhost:8000/tl/newtest/" role="button"> 
			<span class="glyphicon glyphicon-plus" aria-hidden="true" style="font-size:30px"> </span>
		</a>
	</div>

	<div class="col-md-6">
		<p>Informational paragraph</p>
	</div>	
</div>

<div class="row">
	<div class="col-md-6" left-align=True>
	<h3> Current Tests </h3>
	
	{% for test in test_list %}
	    <li><a href='{% url "tl:detail" test.pk %}'> {{ test.test_no }} {{ test.test_name }} </a></li>
	{% endfor %}
	</div>
</div>


{% endblock %}

tl/templates/tl/newtest.html
{% extends 'tl/base.html' %}
{% load crispy_forms_tags %}

{% block content %}


<form enctype="multipart/form-data" method="POST" class="post-form"> {% csrf_token %}

<div class="row">
	<div class="col-md-4">	
  	<h4></h4>
  		<h3>Test Parameters</h3>
		{{ test_form|crispy}}
		{{ sponsor_form|crispy}}
		<br></br>

	  	<h3>Dates</h3>
		{{ wavedate_form|crispy}}
		<br></br>

	 	<h3>Products</h3>
	 	<h4>Tier 1</h4>

		{{ product_form.super_category_tier1|as_crispy_field}}
		{{ product_form.category_tier1|as_crispy_field}}
		{{ product_form.sub_category_tier1|as_crispy_field}}
		{{ product_form.segment_tier1|as_crispy_field}}
		{{ product_form.sku_tier1|as_crispy_field}}
		{{ product_form.group_tier1|as_crispy_field}}

		<br></br>

	 	<h4>Tier 2</h4>

		{{ product_form.super_category_tier2|as_crispy_field}}
		{{ product_form.category_tier2|as_crispy_field}}
		{{ product_form.sub_category_tier2|as_crispy_field}}
		{{ product_form.segment_tier2|as_crispy_field}}
		{{ product_form.sku_tier2|as_crispy_field}}

		<br></br>
	 	<h3>Stores</h3>
		{{ store_form|crispy}}
	</div>
</div>

	<button type="submit" class="save btn btn-default"> Save </button>
</form>


{% endblock %}

tl/templates/tl/query.html
{% extends 'tl/base.html' %}

{% block content %}


<p>{{ context }}</p>


{% endblock %}